
data:
  env: config-server-dev
  user:
    username: adime
    password: '{cipher}AQB5s0BRhZXcSpJVneow/s8SYcg9i1l5SQasjD4lH0NoDs68/6IiLxpvDzlr1pqzurGqE+bn+wI+/DeMghB3LZyrQY42J8Tg6FKLTtz5U5DXZX6YjiC6u41vPDWoA4zI/I0FFAiKh2MpP5eJbeWGQ8jnNVuEzuE4JrEvfX54oUfFhrJxJ/vuv9lkv0MltDMmL+YdF+0cKGfZXiO7ocw0WJGgL/8BsnemUeTn7Kd0O9Y5DaCb/jeKww5e9c+p8TAObnNNON3uQeXqEBgxCG5FN3cX4dWBAiYBHALf2hNDhpFxDq0NIc/FVv0WGhls3/BAVJ66WYMtVE/hBtG5z/GzJYqgbLADTMRprQia/HsDWJflOgz/22wfzTNzsRwxEp83rao='
